gateway:
  replicaCount: 2
  image:
    repository: 394422659307.dkr.ecr.eu-west-1.amazonaws.com/ecommerce/gateway-service
    tag: latest
  service:
    port: 8080
    nodePort: 30080
  env:
    productServiceUrl: "http://product-service:8081"

product:
  replicaCount: 2
  image:
    repository: 394422659307.dkr.ecr.eu-west-1.amazonaws.com/ecommerce/product-service
    tag: latest
  service:
    port: 8081

ingress:
  enabled: true