apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    name: gateway-service
    app: ecommerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{.Values.gateway.service.port}}
      nodePort: {{.Values.gateway.service.nodePort}}
  type: NodePort
  