apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    name: product-service
    app: ecommerce
  ports:
    - protocol: TCP
      port: {{.Values.product.service.port}}
      targetPort: {{.Values.product.service.port}}
  type: ClusterIP
  